#!/bin/bash
#
# @file   add_symbols
# @author David Weber david.weber.dfw@gmail.com
# @date   08/12/2024
#
# @brief add_symbols module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -lt 1 ]; then
  echo "Usage: $0 <symbol directory> [output kicad_sym file]"
  exit -1
fi

if [ $# -eq 2 ]; then
  OUTPUT_FILE="${2}"
else
  OUTPUT_FILE="my_symbols.kicad_sym"
  if [ -f "${OUTPUT_FILE}" ]; then
    read -p "${OUTPUT_FILE} exists - Overwrite? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit -2
  fi
fi

DIR="${1}"

if [ ! -d "${DIR}" ]; then
  echo "${DIR} is not a valid directory"
  exit -1
fi
  
update_kicad_symbols.py "${DIR}"
replace_kicad_symbol_footprint_lib_name "${DIR}"/*.kicad_sym
mk_kicad_symbol_lib.py "${DIR}" > "${OUTPUT_FILE}"
