#!/bin/bash
#
# @file   mk_kicad_proj
# @author David Weber david.weber.dfw@gmail.com
# @date   10/02/2024
#
# @brief mk_kicad_proj module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 3 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: $BASENAME <project dir> <project name> <company name>" > /dev/stderr
  exit 1
fi

if [ ! -n "$KICAD_PROJ_TEMPLATE_DIR" ]; then
  echo "KICAD_PROJ_TEMPLATE_DIR environment variable is not set.  It should point to the directory containing kicad project template files"
  exit 2
else
  echo "KICAD_PROJ_TEMPLATE_DIR=$KICAD_PROJ_TEMPLATE_DIR"
fi

PROJ_DIR=$1
PROJ_NAME=$2
COMPANY=$3
INPUT_DIR="$PROJ_DIR/$PROJ_NAME/input"
TEMPLATE_DIR="$INPUT_DIR/template"
OUTPUT_DIR="$PROJ_DIR/$PROJ_NAME/output"
FAB_DIR="$OUTPUT_DIR/FAB"

echo PROJ_NAME=$1
echo COMPANY=$2
echo PROJ_DIR=$PROJ_DIR
echo INPUT_DIR="$INPUT_DIR"
echo TEMPLATE_DIR="$TEMPLATE_DIR"
echo OUTPUT_DIR="$OUTPUT_DIR"
echo FAB_DIR="$FAB_DIR"

if [ ! -d "$PROJ_DIR" ]; then
  echo "Creating new part number directory: $PCB_DIR"
  mkdir -p ${PROJ_DIR}
else
  echo "Direcotry $PROJ_DIR exists"
fi

if [ -d "$PROJ_DIR/$PROJ_NAME" ]; then
  echo "Error: Project directory $PROJ_DIR/$PROJ_NAME exists!"
  exit 1
else
  mkdir -p $INPUT_DIR
  mkdir -p $OUTPUT_DIR
  mkdir -p $FAB_DIR
fi


cp -R $KICAD_PROJ_TEMPLATE_DIR/* $INPUT_DIR

for suffix in .kicad_prl .kicad_pro .kicad_sch .kicad_pcb; do
  echo "moving $TEMPLATE_DIR${suffix} $INPUT_DIR/${PROJ_NAME}${suffix}"
  mv $TEMPLATE_DIR${suffix} $INPUT_DIR/${PROJ_NAME}${suffix}
done

REVISION="1.0.0"

DATE=`date +"%Y-%m-%d"`

sed -i "s/REV_NUM/$REVISION/" $INPUT_DIR/$PROJ_NAME.*
sed -i "s/DESIGN_TITLE/$PROJ_NAME/" $INPUT_DIR/$PROJ_NAME.*
sed -i "s/DATE/$DATE/" $INPUT_DIR/$PROJ_NAME.*
sed -i "s/COMPANY/$COMPANY/" $INPUT_DIR/$PROJ_NAME.*
 
tree $PROJ_DIR/$PROJ_NAME
