#!/bin/bash
#
# @file   mk_kicad_proj
# @author David Weber david.weber.dfw@gmail.com
# @date   10/02/2024
#
# @brief mk_kicad_proj module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 3 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: $BASENAME <part_number> <revision> <company_name>" > /dev/stderr
  exit 1
fi

if [ ! -n "$KICAD_PROJ_TEMPLATE_DIR" ]; then
  echo "KICAD_PROJ_TEMPLATE_DIR environment variable is not set.  It should point to the directory containing kicad project template files"
  exit 2
else
  echo "KICAD_PROJ_TEMPLATE_DIR=$KICAD_PROJ_TEMPLATE_DIR"
fi

PART_NUMBER=$1
PCB_REV="$2"
COMPANY=$3
PCB_PART_NUMBER="$PART_NUMBER"
PCB_DIR=$PCB_PART_NUMBER
INPUT_DIR=$PCB_DIR/input
MAKEFILE=$INPUT_DIR/Makefile
PCB_TEMPLATE_DIR="$INPUT_DIR/template"

if [ ! -d "$PCB_DIR" ]; then
  echo "Creating new part number directory: $PCB_DIR"
  git ls-remote git@github.com:davidweber/${PCB_PART_NUMBER}
  if [ $? -eq 0 ]; then
    git clone git@github.com:davidweber/${PCB_PART_NUMBER}
    mkdir -p ${INPUT_DIR}
  else
    echo "repo ${PCB_PART_NUMBER} does not exist"
    mkdir -p ${INPUT_DIR}
#    exit -1
  fi
else
  echo "${PCB_DIR} exists"
  exit -2
fi

cp -R ${KICAD_PROJ_TEMPLATE_DIR}/* ${INPUT_DIR}
for suffix in .kicad_prl .kicad_pro .kicad_sch .kicad_pcb; do
  echo "moving $PCB_TEMPLATE_DIR${suffix} $INPUT_DIR/$PCB_PART_NUMBER${suffix}"
  mv $PCB_TEMPLATE_DIR${suffix} $INPUT_DIR/$PCB_PART_NUMBER${suffix}
done
 
DATE=`date +"%Y-%m-%d"`
sed -i "s/REV_NUM/$PCB_REV/" $INPUT_DIR/$PCB_DIR.*
sed -i "s/DESIGN_TITLE/$PCB_PART_NUMBER/" $INPUT_DIR/$PCB_DIR.*
sed -i "s/DATE/$DATE/" $INPUT_DIR/$PCB_DIR.*
sed -i "s/COMPANY/$COMPANY/" $INPUT_DIR/$PCB_DIR.*

mk_kicad_makefile $PCB_PART_NUMBER > $MAKEFILE
 
tree $PCB_DIR
