#!/bin/bash
#
# @file   mk_kicad_proj
# @author David Weber david.weber.dfw@gmail.com
# @date   10/02/2024
#
# @brief mk_kicad_proj module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 4 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: $BASENAME <part_number> <revision> <company_name> <output_dir>" > /dev/stderr
  exit 1
fi

#if [ ! -f "$KICAD_PROJ_TEMPLATE_DIR" ]; then
#  echo "KICAD_PROJ_TEMPLATE_DIR environment variable is not set.  It should point to the directory containing kicad project template files"
#  exit 2
#fi

PART_NUMBER=$1
COMPANY=$3
PROJ_OUTPUT_DIR=$4
PCB_PART_NUMBER="PCB-$PART_NUMBER"
PCBA_PART_NUMBER="PCBA-$PART_NUMBER"
PCB_DIR=$PROJ_OUTPUT_DIR/$PCB_PART_NUMBER
PCBA_DIR=$PROJ_OUTPUT_DIR/$PCBA_PART_NUMBER
PCB_REV="$PCB_PART_NUMBER-$2"
PCB_REV_DIR="$PCB_DIR/$PCB_REV/input"
PCB_TEMPLATE_DIR="$PCB_DIR/$PCB_REV/input/template"
PCBA_REV="$PCBA_PART_NUMBER-$2"
PCBA_REV_DIR="$PCBA_DIR/$PCBA_REV"
OUTPUT_DIR="$PCB_DIR/$PCB_REV/output"
FAB_DIR="$OUTPUT_DIR/FAB"
PCBA_MANIFEST_FILE="$PCBA_REV_DIR/manifest.txt"

if [ ! -d "$PCB_DIR" ]; then
  echo "Creating new part number directory: $PCB_DIR"
  mkdir -p ${PCB_DIR}
else
  echo "$PCB_DIR exists"
fi

if [ -d "$PCB_REV_DIR" ]; then
  echo "Error: Revision directory $PCB_REV_DIR exists, please enter unique revision!"
  exit 1
else
  mkdir -p $PCB_REV_DIR
  mkdir -p $FAB_DIR
  mkdir -p $PCBA_REV_DIR
  echo $'PCB=\nPCBS=\nPCBB=\nPCBF=' > $PCBA_MANIFEST_FILE
fi

cp -R proj_template/* $PCB_REV_DIR
for suffix in .kicad_prl .kicad_pro .kicad_sch .kicad_pcb; do
  echo "moving $PCB_TEMPLATE_DIR${suffix} $PCB_REV_DIR/${PCB_REV}${suffix}"
  mv $PCB_TEMPLATE_DIR${suffix} $PCB_REV_DIR/${PCB_REV}${suffix}
done
 
DATE=`date +"%Y-%m-%d"`
sed -i "s/REV_NUM/$PCB_REV/" $PCB_REV_DIR/$PCB_REV.*
sed -i "s/DESIGN_TITLE/$PCB_PART_NUMBER/" $PCB_REV_DIR/$PCB_REV.*
sed -i "s/DATE/$DATE/" $PCB_REV_DIR/$PCB_REV.*
sed -i "s/COMPANY/$COMPANY/" $PCB_REV_DIR/$PCB_REV.*
 
tree $PCB_DIR
tree $PCBA_DIR
