#!/bin/bash
#
# @file   replace_kicad_symbol_footprint_lib_name
# @author David Weber david.weber.dfw@gmail.com
# @date   08/12/2024
#
# @brief replace_kicad_symbol_footprint_lib_name module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -lt 1 ]; then
  echo "Usage: $0 <file(s)/wildcard>"
  echo $#
  exit -1
else
  sed -i 's/"Footprint" "[^:]*:/"Footprint" "my_footprints:/' "$@"
fi


