#!/bin/bash
#
# @file   update_kicad_title_block
# @author David Weber david.weber.dfw@gmail.com
# @date   11/06/2024
#
# @brief update_kicad_title_block module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 4 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: ${BASENAME} <company> <title> <rev> <file>"
  exit -1
fi

COMPANY=${1}
TITLE=${2}
REV=${3}
FILE=${4}
DATE=`date +%Y-%m-%d`

echo "COMPANY: ${COMPANY}"
echo "TITLE:   ${TITLE}"
echo "REV:     ${REV}"
echo "FILE:    ${FILE}"
echo "DATE:    ${DATE}"

if [ ! -f "${FILE}" ]; then
  echo "Error: ${FILE} not found"
  exit -2
fi

sed \
-i -e 's/company "[^"]*"/company "'"${COMPANY}"'"/' \
-e 's/title "[^"]*"/title "'"${TITLE}"'"/' \
-e 's/date "[^"]*"/date "'"${DATE}"'"/' \
-e 's/rev "[^"]*"/rev "'"${REV}"'"/' \
"${FILE}"

