#!/bin/bash
#
# @file   update_kicad_paper_size
# @author David Weber david.weber.dfw@gmail.com
# @date   11/09/2024
#
# @brief update_kicad_paper_size module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 2 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: ${BASENAME} <paper size> (A1,A2,A3,A4,A5,B,C,D,E) <file>"
  exit -1
fi

PAPER=${1}
FILE=${2}
DATE=`date +%Y-%m-%d`

echo "PAPER: ${PAPER}"
echo "FILE:  ${FILE}"
echo "DATE:  ${DATE}"

if [ ! -f "${FILE}" ]; then
  echo "Error: ${FILE} not found"
  exit -2
fi

sed \
-i -e 's/paper "[^"]*"/paper "'"${PAPER}"'"/' \
-e 's/date "[^"]*"/date "'"${DATE}"'"/' \
"${FILE}"

